// <auto-generated />
using System;
using HospitalAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240609151515_Hospital_DB")]
    partial class Hospital_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalAPI.Models.Drug", b =>
                {
                    b.Property<int>("Drug_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Drug_ID"));

                    b.Property<string>("Drug_AllergyList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Drug_Available")
                        .HasColumnType("bit");

                    b.Property<string>("Drug_Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Drug_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Drug_ID");

                    b.ToTable("DrugSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.Patient", b =>
                {
                    b.Property<int>("Patient_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patient_ID"));

                    b.Property<string>("Patient_Allergy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Patient_DoB")
                        .HasColumnType("date");

                    b.Property<string>("Patient_PhoneNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patient_fName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patient_lName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Patient_ID");

                    b.ToTable("PatientSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.Staff", b =>
                {
                    b.Property<int>("Staff_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staff_ID"));

                    b.Property<bool>("Staff_Active")
                        .HasColumnType("bit");

                    b.Property<int>("Staff_Grade")
                        .HasColumnType("int");

                    b.Property<string>("Staff_PhoneNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Staff_fName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Staff_lName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Staff_ID");

                    b.ToTable("StaffSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.TreatmentPlan", b =>
                {
                    b.Property<int>("Plan_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Plan_ID"));

                    b.Property<int>("Patient_ID")
                        .HasColumnType("int");

                    b.Property<int>("Plan_CycleLen")
                        .HasColumnType("int");

                    b.Property<DateTime>("Plan_Date")
                        .HasColumnType("date");

                    b.Property<string>("Plan_Observation")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Plan_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Staff_ID")
                        .HasColumnType("int");

                    b.HasKey("Plan_ID");

                    b.ToTable("TreatmentPlanSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.TreatmentPlanEntry", b =>
                {
                    b.Property<int>("Entry_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Entry_ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Drug_ID")
                        .HasColumnType("int");

                    b.Property<string>("Entry_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("date");

                    b.Property<int>("Plan_ID")
                        .HasColumnType("int");

                    b.Property<string>("Posology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Staff_ID")
                        .HasColumnType("int");

                    b.Property<string>("UploadLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Entry_ID");

                    b.ToTable("TreatmentPlanEntrySet");
                });
#pragma warning restore 612, 618
        }
    }
}
