// <auto-generated />
using System;
using HospitalAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240310220911_Hospital_DB")]
    partial class Hospital_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalAPI.Models.Drug", b =>
                {
                    b.Property<int>("Drug_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Drug_ID"));

                    b.Property<string>("Drug_AllergyList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Drug_ID");

                    b.ToTable("DrugSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.MedicationPlan", b =>
                {
                    b.Property<int>("MPlanEntry_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MPlanEntry_ID"));

                    b.Property<int>("Drug_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MedPlan_Date")
                        .HasColumnType("date");

                    b.Property<int>("MedPlan_ID")
                        .HasColumnType("int");

                    b.Property<string>("MedPlan_Posology")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MPlanEntry_ID");

                    b.ToTable("MedicationPlanSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.Patient", b =>
                {
                    b.Property<int>("Patient_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patient_ID"));

                    b.Property<string>("Patient_Allergy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Patient_DoB")
                        .HasMaxLength(50)
                        .HasColumnType("date");

                    b.Property<int>("Patient_PhoneNum")
                        .HasColumnType("int");

                    b.Property<string>("Patient_fName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patient_lName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Patient_ID");

                    b.ToTable("PatientSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.Staff", b =>
                {
                    b.Property<int>("Staff_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Staff_ID"));

                    b.Property<int>("Staff_Grade")
                        .HasColumnType("int");

                    b.Property<int?>("Staff_PhoneNum")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Staff_fName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Staff_lName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Staff_ID");

                    b.ToTable("StaffSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.TestResult", b =>
                {
                    b.Property<string>("TestRes_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Staff_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestRes_Date")
                        .HasColumnType("date");

                    b.Property<string>("TestRes_Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestRes_Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestRes_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestRes_ID");

                    b.ToTable("TestResultSet");
                });

            modelBuilder.Entity("HospitalAPI.Models.TreatmentPlan", b =>
                {
                    b.Property<int>("TPlanEntry_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TPlanEntry_ID"));

                    b.Property<int>("Patient_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Plan_Date")
                        .HasColumnType("date");

                    b.Property<int>("Plan_ID")
                        .HasColumnType("int");

                    b.Property<int>("Staff_ID")
                        .HasColumnType("int");

                    b.Property<int>("TPlan_ActionLink")
                        .HasColumnType("int");

                    b.Property<string>("TPlan_ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TPlan_CycleLen")
                        .HasColumnType("int");

                    b.Property<string>("TPlan_Observation")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("TPlan_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TPlanEntry_ID");

                    b.ToTable("TreatmentPlanSet");
                });
#pragma warning restore 612, 618
        }
    }
}
